### ISSUE TITLE
mwscrape --changes-since and --recent no feedback

### ISSUE THREAD

**Issue by MHBraun** [itkach/mwscrape#11]
Using
time mwscrape de.m.wikipedia.org --delete-not-found --changes-since 20150802
or
time mwscrape de.m.wikipedia.org --delete-not-found --recent --recent-days 14
do not provide a feedback (screen listing) of the collected articles.

The output
Starting session de-m-wikipedia-org-1439950680-485
does not create the document in mwscrape 
The scrape stops after approximately 2h

Therefore I guess no data is collected.

**Comment by itkach** [comment]
I don't think this is relevant anymore, closing
