### ISSUE TITLE
does --recent collect all changes?

### ISSUE THREAD

**Issue by MHBraun** [itkach/mwscrape#12]
A user came up with the following finding in dewiki:

Article Westerwelle Guido
his death was entered in Wikipedia on the same day at March 18 2016. However it did not show up in April nor in May compilation of dewiki data. The log files I create do not show any change of Westerwelle.
Article Genscher Hans-Dietrich
died on March 31 2016, his data was in April and May dewiki. The log files do not show any change of Genscher.

The scrape of dewiki runs as a cron job once a day:

`mwscrape $couchdb --delete-not-found --recent --recent-days 21 2>&1 | tee /home/guest/dewi-$Datum.log`

where` $couchdb` is de-m-wikipedia-org
and `$Datum `is the actual date.
The `2>&1 | tee` does redirect the output of the scrape as well onto the screen as into the logfile.
This way I have an overlap of 21 days on items I would not capture the first time or any broken connections during scraping.

Nevertheless Genscher was updated correctly, but Westerwelle not.

It is virtually impossible to check if the changes made are completely scraped.
Any thoughts?

**Comment by francwalter** [comment]
Oh! This will then also concern the frwiki I guess.

**Comment by itkach** [comment]
I took another look at MediaWiki recent changes api and what it returns. 

Just one day worth of changes for enwiki came back with ~594 thousand titles - more than entire Wikipedias in many other languages, so it looks rather suspicious. Minor changes, anonymous edits and redirect pages are already ignored, but I noticed that bot edits can also be filtered out, so with that change it came down  to ~380 thousand titles - still a suspiciously large number. Both dewiki and frwiki don't seem to get that many bot edits and reported around 80 thousand changed titles regardless of ignoring bot edits. 

Another observation is that by default (and that's what mwscrape was using) the api returns changes in reverse chronological order (https://www.mediawiki.org/wiki/API:RecentChanges). So while we are processing changed articles and slowly moving through the list of titles, the list changes on us, with new changes coming in to the start of the list which we already processed. That's my theory as to why some changes may have gone unprocessed. I changed mwscrape (6a58d7801eb1e884fd0516f1adbedbd4481c10e6) to filter out bot edits and to request older changes first. If my understanding is correct I think it should address the issue. (Note that timestamp that is now printed when new revision is found is in UTC and this is when the page was last "touched", which is not necessarily an edit, could be other things like changed permissions)

However, if the api correctly reports changes and there are indeed so many legitimate edits, then it's probably better to just run a regular scrape, certainly for enwiki, but probably for other large wikis as well.

**Comment by MHBraun** [comment]
The impact will be on any database which is updated with --recent

The question is how big is the impact. If the error is minor I guess we may just live with it. If it is serious we need to rescrape the whole database one and a while.


-------- Ursprüngliche Nachricht --------
Von: franc <notifications@github.com> 
Datum:09.05.2016  16:19  (GMT-06:00) 
An: itkach/mwscrape <mwscrape@noreply.github.com> 
Cc: MHBraun <mhbraun@web.de>, Author <author@noreply.github.com> 
Betreff: Re: [itkach/mwscrape] does --recent collect all changes? (#12) 

Oh! This will then also concern the frwiki I guess.

**Comment by francwalter** [comment]
So first I will update mwscrape. 
Done.

So best is now to rescrape the whole frwiki + frwiktionary?
How can I test if the mwscrape with --recent will now be correct?

**Comment by MHBraun** [comment]
Thank you for looking into it, Igor.

Here are my observations: Having found around 20% changed articles according to mwscrape log in couch with a full scrape ongoing for dewiki. The couch database was updated with --recent parameters only since last December edition. Now the full scrape is showing up to 20% additional changes which were obviously not picked by the --recent scrapes.

The log I am generating for a --recent scrape is listing for

- enwiki approximately 20 000 updates per day
- dewiki approximately 2 000 updates per day

which are captured and logged.

This is much lower than the value you found. The interesting changes are the changes within the article of course.

One comment to your theory above:
I am scraping overlapped. In case the scrape breaks, it may collect the uncollected data with the next scrape. 
Using --recent-days 21 and scraping every second day does give me a decent and safe overlapping. Any new changes which are flowing in during the scrape would be picked up with the next scrape. This is the theory. Not sure if it works this way.
