### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by yegorich** [itkach/mwscrape#13]
Is Python 3 support planned? AFAIK **mwclient** already supports Python 3 in its resent version. So all **mwscrape** dependencies already support Python 3.

This issue is very important for such environments as for example [Buildroot](https://buildroot.org/), that support only one Python instance (either python 2 or python 3) at a time.

2to3 tools found several needed changes:
- python 3 incompatible print statements
- urllib package was renamed in python 3
- thread package was also renamed (_thread)

I'm not a user of mwscrape but rather a co-maintainer of various python packages in Buildroot. So it would be great, if you could fix this issue.

Thanks.

**Comment by itkach** [comment]
I pushed initial port to Python 3 in py3 branch, and it sort of works, however I ran into this issue: https://github.com/djc/couchdb-python/issues/281. It seems that ultimately CouchDB is the project that should fix it (https://issues.apache.org/jira/browse/COUCHDB-3003), or perhaps Python's httplib one day will become more lenient again, but until then mwscrape on Python 3 isn't really usable.

**Comment by itkach** [comment]
fixed with ccbfc31ca96472f7f34db908e521538b277a19c1  7c37169bd1c845a40e595d1e3b510578582113e1 etc
