### ISSUE TITLE
enable usage of https://dumps.wikimedia.org/

### ISSUE THREAD

**Issue by drogga3** [itkach/mwscrape#19]
why scrape an online instance of mediawiki when you can do it offline?

**Comment by itkach** [comment]
Previous generation of aard dictionary/[tools](https://github.com/aarddict/tools) did just [ that](https://github.com/aarddict/tools/blob/master/aardtools/wiki/wiki.py), however as Wikipedia evolved it became increasingly more difficult to maintain and generally impossible to achieve parity in rendering quality with [Mediawiki](https://en.wikipedia.org/wiki/MediaWiki) (software that powers Wikipedia sites). The key elements that make it so are incredible complexity of wiki [markup](https://en.wikipedia.org/wiki/MediaWiki#Markup) and [templating language](https://en.wikipedia.org/wiki/MediaWiki#Templates), introduction of [Lua-based templates](https://en.wikipedia.org/wiki/MediaWiki#Text_manipulation) and migration of factual data (for [infoboxes](https://en.wikipedia.org/wiki/Help:Infobox) and perhaps other page elements) to a database. To put it short, only Mediawiki can properly render Mediawiki content. So getting the rendered content directly from a Mediawiki site via provided api is the only viable option.

**Comment by drogga3** [comment]
Fair point. I guess that's the only way to do it now. Thank you for the thorough explaination.
