### ISSUE TITLE
Not possible to login to CouchDB

### ISSUE THREAD

**Issue by francwalter** [itkach/mwscrape#7]
In the [doc of CouchDB](http://docs.couchdb.org/en/1.6.1/config/auth.html) I can read that it were "wise" to create an admin to restrict the full access to the couchdb, and in the fresh couchdb installation in **Futon on Apache CouchDB 1.6.1** I can read at the bottom right:
**Welcome to Admin Party!
Everyone is admin. [Fix this](http://localhost:5985/_utils/index.html#)**
But in mwscrape it seems to be not possible to use parameters as login to a secured CouchDB.
Without login I get an error:
**couchdb.http.Unauthorized: (u'unauthorized', u'You are not a server admin.')**

**Comment by itkach** [comment]
The main use case for mwscrape is to populate couchdb running locally or on trusted local network, these couchdb instances were never meant to be open to the world. But it's not difficult to pass username and password on to couchdb client, I'll add that.

**Comment by francwalter** [comment]
Great, many thanks advancly :)

**Comment by itkach** [comment]
Fixed in ae8a0d38f6bd01b948e9febc8b95bddd56c1fdcc
